# Generated by Django 2.2.5 on 2020-01-23 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tofunmiscrumy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalstatus',
            name='status_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='created_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='goal_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='moved_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='owner',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_goal', to=settings.AUTH_USER_MODEL),
        ),
    ]
